---
pools:
  - multipools:
    - name: ahashpool
      enabled: true
    - name: blazepool
      enabled: true
    - name: hashrefinery
      enabled: true
    - name: zergpool
      enabled: true
    - name: zpool
      enabled: true
  - custompools:
    - name: pigonpool
      strato:
        url: http://pigeonpool.com
        worker_name: worker1
        worker_password: PBhzfEEBfBFyGjTBrUaYwaTuJJzXT1JKFH
wallets:
  - name: BTC Mining
    Coin: BTC
    Address: 19ZH5VYJKvEXCkAayNxURhSXCRnNnAQ8K5
  - name: PGN Mining
    Coin: PGN
    Address: PBhzfEEBfBFyGjTBrUaYwaTuJJzXT1JKFH
  - name: RVN Mining
    Coin: RVN
    Address: RPJpvk4KXwd6occZvrqwce1ZrC9yhSPnwU
  - name: HTM Mining
    Coin: HTH
    Address: HFSL8DxxZ9ABHHbb6WzPrNNwbkiPHfmR66
